blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://gruke.readthedocs.io/en/latest/introduction
    about: Read our comprehensive documentation.
  - name: 🚀 First-Class Support
    url: https://github.com/sponsors/GreemDev?frequency=one-time
    about: Make a sponsorship to receive professional support.
