name: Deploy Docs

on:
  push:
    tags:
      - '*'
    branches:
      - 'develop'
    paths:
      - 'docs/**'
      - 'source/**'
      - 'README.md'
      - "build/Build.DocFX.cs"
  workflow_dispatch:
    inputs: {}
jobs:
  build:
    name: Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: 'Cache: .nuke/temp, ~/.nuget/packages'
      uses: actions/cache@v5
      with:
        path: |
          .nuke/temp
          ~/.nuget/packages
        key: docfx-${{ hashFiles('**/global.json', '**/*.csproj', '**/Directory.Packages.props') }}

    - name: 'Run: DocFX'
      run: ./build.cmd DocFX

    - name: Push to the Docs Repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.DOCFX_GITHUB_TOKEN }}
      with:
        source-directory: 'docs/generated'
        destination-github-username: 'gruke-build'
        destination-repository-name: 'docs'
        user-name: "GitHub Actions on behalf of GreemDev"
        user-email: greemdev@ryujinx.app
        target-branch: docfx
        target-directory: docs